# Generated by Django 4.1.1 on 2022-09-20 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productcategory_classification_characteristics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialproduct',
            name='description',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productcategory'),
        ),
    ]
