# Generated by Django 4.1.1 on 2022-09-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='raiting',
            new_name='rating',
        ),
    ]
