# Generated by Django 4.1.1 on 2022-09-24 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_brand_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialproduct',
            name='characteristic_value',
        ),
        migrations.AddField(
            model_name='brand',
            name='icon',
            field=models.ImageField(null=True, upload_to='brand/icon/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to='brand/image/'),
        ),
        migrations.AddField(
            model_name='product',
            name='main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_main', to='shop.product'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='product/category/'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='image',
            field=models.ImageField(upload_to='product/image/'),
        ),
        migrations.AlterField(
            model_name='reviewphoto',
            name='image',
            field=models.ImageField(upload_to='comment/image'),
        ),
    ]
