# Generated by Django 4.1.1 on 2022-09-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_productimage_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='characteristic_value',
        ),
    ]
